services:
  ping:
    build:
      context: ./ping
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    networks:
      - pingpong
  pong:
    build:
      context: ./pong
      dockerfile: Dockerfile
    ports:
      - "1235:1235"
    networks:
      - pingpong

networks:
  pingpong:
    driver: bridge